return (async () => {
  const pause = () => new Promise(resolve => setTimeout(resolve, 20));
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  const selection = () => document.querySelector('.book-page-select select');
  const choose = async index => { const select = selection(); select.value = String(index); select.dispatchEvent(new Event('change', { bubbles: true })); await pause(); };
  await choose(0);
  assert(document.querySelector('.book-prev-button').disabled, 'Back must be disabled on page 180');
  document.querySelector('.book-next-button').click();
  await pause();
  assert(selection().value === '1', 'Next should show PDF181');
  document.querySelector('.book-prev-button').click();
  await pause();
  assert(selection().value === '0', 'Back should show PDF180');
  document.querySelector('.book-page-viewport').focus();
  window.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  await pause();
  assert(selection().value === '1', 'ArrowRight should advance');
  selection().focus();
  selection().dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  await pause();
  assert(selection().value === '1', 'Keyboard must not interfere with select');
  await choose(29);
  assert(document.querySelector('.book-next-button').disabled, 'Next must be disabled on PDF209');
  assert(document.querySelector('.book-page-counter').textContent.includes('209'), 'Last page label incorrect');
  const widthBefore = parseFloat(document.querySelector('.book-page-image').style.width);
  document.querySelector('[aria-label="Perbesar halaman"]').click();
  await pause();
  assert(parseFloat(document.querySelector('.book-page-image').style.width) > widthBefore, 'Zoom should enlarge image');
  assert(document.querySelector('.book-fullscreen-dialog')?.open, 'Zoom must open full-screen reader');
  document.querySelector('[aria-label="Pas halaman"]').click();
  await pause();
  assert(document.querySelector('.book-zoom-value').textContent === '100%', 'Fit page should reset zoom');
  const pageBase = new URL(document.querySelector('.book-page-image').src);
  const pages = await Promise.all(Array.from({ length: 30 }, (_, i) => new Promise(resolve => {
    const image = new Image();
    image.onload = () => resolve({ page: 180 + i, width: image.naturalWidth, height: image.naturalHeight });
    image.onerror = () => resolve({ page: 180 + i, error: true });
    image.src = new URL(`page-${180 + i}.webp`, pageBase).href;
  })));
  assert(pages.every(page => !page.error && page.width > 1000), 'Some slides failed to load');
  await choose(0);
  document.querySelector('[aria-label="Tutup layar penuh"]').click();
  await pause();
  return { slidesLoaded: pages.length, navigation: 'passed', keyboard: 'passed', boundaries: 'passed', zoom: 'passed', persistedPage: localStorage.getItem('kanji-uts-book-page-v2'), overflow: document.documentElement.scrollWidth > innerWidth };
})();
